// <auto-generated />
namespace CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class delblogformclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delblogformclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201611131417557_del-blog-form-class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
