CREATE TABLE ADMIN.LINEITEM_ORDERKEY
(
	L_ORDERKEY INTEGER NOT NULL,
	L_PARTKEY INTEGER NOT NULL,
	L_SUPPKEY INTEGER NOT NULL,
	L_LINENUMBER INTEGER NOT NULL,
	L_QUANTITY NUMERIC(15,2) NOT NULL,
	L_EXTENDEDPRICE NUMERIC(15,2) NOT NULL,
	L_DISCOUNT NUMERIC(15,2) NOT NULL,
	L_TAX NUMERIC(15,2) NOT NULL,
	L_RETURNFLAG CHARACTER(1) NOT NULL,
	L_LINESTATUS CHARACTER(1) NOT NULL,
	L_SHIPDATE DATE NOT NULL,
	L_COMMITDATE DATE NOT NULL,
	L_RECEIPTDATE DATE NOT NULL,
	L_SHIPINSTRUCT CHARACTER(25) NOT NULL,
	L_SHIPMODE CHARACTER(10) NOT NULL,
	L_COMMENT CHARACTER VARYING(44) NOT NULL
)
DISTRIBUTE ON (L_ORDERKEY);


CREATE TABLE ADMIN.LINEITEM_RANDOM
(
	L_ORDERKEY INTEGER NOT NULL,
	L_PARTKEY INTEGER NOT NULL,
	L_SUPPKEY INTEGER NOT NULL,
	L_LINENUMBER INTEGER NOT NULL,
	L_QUANTITY NUMERIC(15,2) NOT NULL,
	L_EXTENDEDPRICE NUMERIC(15,2) NOT NULL,
	L_DISCOUNT NUMERIC(15,2) NOT NULL,
	L_TAX NUMERIC(15,2) NOT NULL,
	L_RETURNFLAG CHARACTER(1) NOT NULL,
	L_LINESTATUS CHARACTER(1) NOT NULL,
	L_SHIPDATE DATE NOT NULL,
	L_COMMITDATE DATE NOT NULL,
	L_RECEIPTDATE DATE NOT NULL,
	L_SHIPINSTRUCT CHARACTER(25) NOT NULL,
	L_SHIPMODE CHARACTER(10) NOT NULL,
	L_COMMENT CHARACTER VARYING(44) NOT NULL
)
DISTRIBUTE ON RANDOM;


CREATE TABLE ADMIN.LINEITEM_SHIPDATE
(
	L_ORDERKEY INTEGER NOT NULL,
	L_PARTKEY INTEGER NOT NULL,
	L_SUPPKEY INTEGER NOT NULL,
	L_LINENUMBER INTEGER NOT NULL,
	L_QUANTITY NUMERIC(15,2) NOT NULL,
	L_EXTENDEDPRICE NUMERIC(15,2) NOT NULL,
	L_DISCOUNT NUMERIC(15,2) NOT NULL,
	L_TAX NUMERIC(15,2) NOT NULL,
	L_RETURNFLAG CHARACTER(1) NOT NULL,
	L_LINESTATUS CHARACTER(1) NOT NULL,
	L_SHIPDATE DATE NOT NULL,
	L_COMMITDATE DATE NOT NULL,
	L_RECEIPTDATE DATE NOT NULL,
	L_SHIPINSTRUCT CHARACTER(25) NOT NULL,
	L_SHIPMODE CHARACTER(10) NOT NULL,
	L_COMMENT CHARACTER VARYING(44) NOT NULL
)
DISTRIBUTE ON (L_SHIPDATE);


CREATE TABLE ADMIN.ORDERS_ORDERKEY
(
	O_ORDERKEY INTEGER NOT NULL,
	O_CUSTKEY INTEGER NOT NULL,
	O_ORDERSTATUS CHARACTER(1) NOT NULL,
	O_TOTALPRICE NUMERIC(15,2) NOT NULL,
	O_ORDERDATE DATE NOT NULL,
	O_ORDERPRIORITY CHARACTER(15) NOT NULL,
	O_CLERK CHARACTER(15) NOT NULL,
	O_SHIPPRIORITY INTEGER NOT NULL,
	O_COMMENT CHARACTER VARYING(79) NOT NULL
)
DISTRIBUTE ON (O_ORDERKEY);


CREATE TABLE LABADMIN.CUSTOMER
(
	C_CUSTKEY INTEGER NOT NULL,
	C_NAME CHARACTER VARYING(25) NOT NULL,
	C_ADDRESS CHARACTER VARYING(40) NOT NULL,
	C_NATIONKEY INTEGER NOT NULL,
	C_PHONE CHARACTER(15) NOT NULL,
	C_ACCTBAL NUMERIC(15,2) NOT NULL,
	C_MKTSEGMENT CHARACTER(10) NOT NULL,
	C_COMMENT CHARACTER VARYING(117) NOT NULL
)
DISTRIBUTE ON (C_CUSTKEY);


CREATE TABLE LABADMIN.LINEITEM
(
	L_ORDERKEY INTEGER NOT NULL,
	L_PARTKEY INTEGER NOT NULL,
	L_SUPPKEY INTEGER NOT NULL,
	L_LINENUMBER INTEGER NOT NULL,
	L_QUANTITY NUMERIC(15,2) NOT NULL,
	L_EXTENDEDPRICE NUMERIC(15,2) NOT NULL,
	L_DISCOUNT NUMERIC(15,2) NOT NULL,
	L_TAX NUMERIC(15,2) NOT NULL,
	L_RETURNFLAG CHARACTER(1) NOT NULL,
	L_LINESTATUS CHARACTER(1) NOT NULL,
	L_SHIPDATE DATE NOT NULL,
	L_COMMITDATE DATE NOT NULL,
	L_RECEIPTDATE DATE NOT NULL,
	L_SHIPINSTRUCT CHARACTER(25) NOT NULL,
	L_SHIPMODE CHARACTER(10) NOT NULL,
	L_COMMENT CHARACTER VARYING(44) NOT NULL
)
DISTRIBUTE ON (L_LINESTATUS);


CREATE TABLE LABADMIN.NATION
(
	N_NATIONKEY INTEGER NOT NULL,
	N_NAME CHARACTER(25) NOT NULL,
	N_REGIONKEY INTEGER NOT NULL,
	N_COMMENT CHARACTER VARYING(152)
)
DISTRIBUTE ON (N_NATIONKEY);


CREATE TABLE LABADMIN.ORDERS
(
	O_ORDERKEY INTEGER NOT NULL,
	O_CUSTKEY INTEGER NOT NULL,
	O_ORDERSTATUS CHARACTER(1) NOT NULL,
	O_TOTALPRICE NUMERIC(15,2) NOT NULL,
	O_ORDERDATE DATE NOT NULL,
	O_ORDERPRIORITY CHARACTER(15) NOT NULL,
	O_CLERK CHARACTER(15) NOT NULL,
	O_SHIPPRIORITY INTEGER NOT NULL,
	O_COMMENT CHARACTER VARYING(79) NOT NULL
)
DISTRIBUTE ON RANDOM;


CREATE TABLE LABADMIN.PART
(
	P_PARTKEY INTEGER NOT NULL,
	P_NAME CHARACTER VARYING(55) NOT NULL,
	P_MFGR CHARACTER(25) NOT NULL,
	P_BRAND CHARACTER(10) NOT NULL,
	P_TYPE CHARACTER VARYING(25) NOT NULL,
	P_SIZE INTEGER NOT NULL,
	P_CONTAINER CHARACTER(10) NOT NULL,
	P_RETAILPRICE NUMERIC(15,2) NOT NULL,
	P_COMMENT CHARACTER VARYING(23) NOT NULL
)
DISTRIBUTE ON (P_PARTKEY);


CREATE TABLE LABADMIN.PARTSUPP
(
	PS_PARTKEY INTEGER NOT NULL,
	PS_SUPPKEY INTEGER NOT NULL,
	PS_AVAILQTY INTEGER NOT NULL,
	PS_SUPPLYCOST NUMERIC(15,2) NOT NULL,
	PS_COMMENT CHARACTER VARYING(199) NOT NULL
)
DISTRIBUTE ON (PS_PARTKEY);


CREATE TABLE LABADMIN.REGION
(
	R_REGIONKEY INTEGER NOT NULL,
	R_NAME CHARACTER(25) NOT NULL,
	R_COMMENT CHARACTER VARYING(152)
)
DISTRIBUTE ON (R_REGIONKEY);


CREATE TABLE LABADMIN.SUPPLIER
(
	S_SUPPKEY INTEGER NOT NULL,
	S_NAME CHARACTER(25) NOT NULL,
	S_ADDRESS CHARACTER VARYING(40) NOT NULL,
	S_NATIONKEY INTEGER NOT NULL,
	S_PHONE CHARACTER(15) NOT NULL,
	S_ACCTBAL NUMERIC(15,2) NOT NULL,
	S_COMMENT CHARACTER VARYING(101) NOT NULL
)
DISTRIBUTE ON (S_SUPPKEY);


